# Generated by Django 4.2.1 on 2023-06-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Curso', models.CharField(max_length=50)),
                ('Procedencia', models.CharField(max_length=50)),
                ('Matricula', models.CharField(blank=True, max_length=50)),
                ('Institucion', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=50)),
                ('Pais', models.CharField(max_length=50)),
                ('Municipio', models.CharField(max_length=50)),
                ('EstadoCivil', models.CharField(max_length=15)),
            ],
        ),
    ]
